### ISSUE TITLE
[Feature Request] Crawl Subreddit

### ISSUE THREAD

**Issue by deltakapp** [deltakapp/products-from-reddit#7]
## Goal

To retrieve post data from an arbitrary subreddit, sorted by new

### Context

This data should be ready to be parsed - simply fetched and returned by function

## Success Criteria

This should be formatted as a function that takes arguments:
- subreddit name
- depth of crawl (number of posts to retrieve) (with an appropriate default)
This function should return data as a pandas dataframe

### Out of Scope

This should not attempt to parse, filter, or store data.

## Notes and Resources

re-retrieving specific posts for updates may later become in scope for this or other functions.

**Comment by ErinMyLungs** [comment]
## Short TODO list

* [ ] Implement secrets approach for configuring sensitive credentials
  * [ ] Make sure credentials cannot be committed to the repo!
* [ ] Create method to iterate through `/r/hardwareswap` posts sorted by new
* [ ] Create `_save_reddit_post` method

Specifics on the implementation and each section are included below. Please let me know if any of this needs further clarification. If you are unsure on something, it's always a great idea to ask for feedback/questions or to propose an approach you think would work.

## Crawler implementation

In general a crawler should work like this:
* Iterates over posts in /r/hardwareswap (or any subreddit) sorted by `new`
* Saves each post into a `.json` file with the data:
  * Full title
  * post ID
  * Full text of the main post
  * Creation date
  * Updated at date
  * We should also create a new field of `crawled_at` which includes the current datetime the post information was accessed.
    * Keeping this information is crazy useful for debugging and is easy to forget to include. Seriously, I never realized how useful this was until I really needed this info.
* Take in a `end_date` parameter which controls how far back the crawl goes until stopping.

This core functionality can then be crafted to make both the `full` and `incremental` crawl commands.

Here is a pseudo-code approach of what it could look like:

```python
@click.group()
def crawl():
  pass

def _crawl(end_date: datetime) -> None:
  for reddit_post in RedditAPI.search("/hardwareswap").sort_by("new"):
    if reddit_post['creation_date'] <= end_date:
      return

    reddit_post_json = {
      "title": reddit_post["title"],
      "description": reddit_post["description"],
      "post_id": reddit_post['id'],
      "crawled_at": datetime.now().isoformat(),
      "created_at": reddit_post["created_at"],
      "updated_at": reddit_post['updated_at'],
    }

    print(f"Saving reddit post {reddit_post['id']}")
    _save_reddit_post(reddit_post_json)

@crawl.command()
def full():
  end_date = datetime.now() - timedelta(days=365)
  _crawl(end_date)

@crawl.command()
def incremental():
  end_date = datetime.now() - timedelta(days=2)
  _crawl(end_date)
```

Note the `RedditAPI` search bit is entirely pseudocode and likely doesn't match the interface you're using. Basically substitute it with however you currently iterate through the API to pull posts.

Essentially it's just working through each post and writing them individually to file.

### Crawling subreddit posts implementation

I'll leave this mostly up to you. If you pull all the posts into a pandas dataframe then you can use
```python
reddit_posts_dataframe.to_dict(orient="records")
```
to get each row as a dictionary with the columns as the keys and the cells as the values.

If you wanted to get really fancy, you could filter out the rows that aren't created after the `end_date` but doing it with the dictionaries is solid too.

### Credentials piece

I'm a fan of having `secrets.py` in the `.gitignore` file and having an `example_secrets.py` file which includes what secrets are required to be filled out for the program to run. It makes it easy to copy the file and fill it out when setting up the repo.

### Save function specifics
If I remember right, the reddit post ID is unique, so for now just save each post to a json file that uses the reddit ID as the name.

Ex: https://old.reddit.com/r/hardwareswap/comments/10s7smo/usany_h_full_white_rog_strix_build_everything/

This post would be saved to a file `10s7smo.json` with the following contents: (the dates are made up)

```json
{
  "title": "[USA-NY] [H] Full white ROG Strix Build, everything included! [W] Local Cash",
  "description": "Hey folks! I am moving away from gaming and streaming...",
  "post_id": "10s7smo",
  "crawled_at": "2023-02-03T21:00:00+00:00",
  "created_at": "2023-02-03T01:54:30+00:00",
  "updated_at": null
}
```

I'd suggest having the data be saved to a directory `data` directly under the repo main directory.
